# Generated by Django 4.1.7 on 2023-03-10 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_condition_item_condition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listing',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_theme', to='auctions.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_theme', to='auctions.theme'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_condition', to='auctions.condition'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_title', to='auctions.item'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_year', to='auctions.item'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('item_id', 'item_name', 'item_year', 'item_theme')},
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_category',
        ),
    ]
