# Generated by Django 4.1.7 on 2023-03-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_item_unique_together_listing_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='year',
        ),
        migrations.AlterField(
            model_name='listing',
            name='url_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
