# Generated by Django 4.1.7 on 2023-03-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_theme_remove_listing_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_url_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
