# Generated by Django 4.1.7 on 2023-03-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_theme_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active_listing',
            field=models.BooleanField(default=True),
        ),
    ]
