# Generated by Django 4.1.7 on 2023-03-17 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_bid_bid_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
